name: Update README with Repo Stats

on:
  schedule:
    - cron: '0 * * * *'  
  workflow_dispatch:  
  push:
    branches:
      - test-branch  

jobs:
  update-readme:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Update README.md
        run: |
          python3 update_readme.py

      - name: Commit and push changes if README.md is updated
        run: |
          git config --global user.name "GitHub Action"
          git config --global user.email "action@github.com"
          git remote set-url origin https://x-access-token:${{ secrets.GITHUB_TOKEN }}@github.com//SkalaFrost/SkalaFrost.git
          git checkout test-branch
          git commit -am "Update readme"
          git push